### PR TITLE
Add all miscellaneous npm modules

### PR DESCRIPTION
**Pull request by christianbundy**
This might be a bit too much miscellaneous content (maybe it should be removed from `SUMMARY.md`?), but I've added the rest of the SSBC modules. They haven't been organized so I've just added them to a "miscellaneous" section, as long as the repo contained:

- a `package.json`
- a `README.md`
- no `book.js*`

Thanks to @ahdinosaur to pointing out how easy this would be with a mechanical edit.

1. Find packages from meta repo with [script](https://github.com/christianbundy/ssbc-meta/blob/master/_scripts/modules.sh):
    ```sh
    meta exec "$(< _scripts/modules.sh)"
    ```
2. Generate Markdown links from the modules.scuttlebutt.nz repo:
    ```sh
    dir=misc;
    for file in $(ls $dir);
      do name=${file%.md}; echo "* [$name]($dir/$file)";
    done
    ```

### CODE REVIEW

**Comment by mixmix** [comment]
Cool. I think the automation does a bunch of typing. I want to cherry pick from this into relevant sections. I don't really want to add dud-repos (dead, deprecated .. or maybe that should be a section in itself?)

I think this repo should be a base and people can / could move things around based on it

**Comment by mixmix** [comment]
Cool, that was useful, have plucked some of those already

**Comment by mixmix** [comment]
(and merged in master)

**Comment by christianbundy** [comment]
> I want to cherry pick from this into relevant sections. I don't really want to add dud-repos (dead, deprecated .. or maybe that should be a section in itself?)

Same, I'd love to figure out which repos are duds but I was having trouble coming up with a heuristic to figure it out without having to use my human brain. :robot:

**Comment by mixmix** [comment]
Others should feel free to cherry pick from this branch as well btw!

**Comment by christianbundy** [comment]
I'm going to close this PR but leave the branch. :~)

**Pull request closed without merging**
